services:
  app:
    build:
      context: .
    #find dockerfile to take image as a base
    volumes:
      - ./src:/app
    # mount src folder to the volume in app to take changes
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "python manage.py runserver 0.0.0.0:8000 --settings=config.settings.development"

  db:
    image: postgres:17.2-alpine3.21
    ports:
      - "5555:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - app
      - redis
    command: sh -c "celery -A config worker --loglevel=INFO"

  flower:  # celery interface to track tasks
    build:
      context: .
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - app
      - redis
    command: sh -c "celery -A config flower"
    ports:
      - "5557:5555"

  celery-beat:
    build:
      context: .
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - app
      - redis
    command: sh -c "celery -A config beat"

volumes:
  db_data:
  # volume in the host
  