# Generated by Django 5.1 on 2025-01-19 17:45

import account.models.forgot_password_token
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rename_userfollowers_userfollowermodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForgotPasswordTokenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expired_at",
                    models.DateTimeField(
                        default=account.models.forgot_password_token.get_expiry_date
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forgot_password_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forgot_password_token",
                "verbose_name_plural": "Forgot_password_tokens",
                "db_table": "forgot_password_token",
            },
        ),
    ]
