# Generated by Django 5.1 on 2024-12-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bookmarkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_articles', to='blog.articlemodel', verbose_name='article'),
        ),
    ]
